name: GitHub-Actions
on:
  - push
  - pull_request

jobs:
  build-and-lint-and-test :
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses:  actions/checkout@v3
    
      - name: Install poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          make install

      - name: Check lint
        run: make lint

      - name: Chek tests
        run: make test

      - name: Check console command gendiff
        run: gendiff -h

      - name: Test-coverage and publish CodeCoverage
        uses: paambaati/codeclimate-action@v5
        # Add Code Climate key
        env:
          CC_TEST_REPORTER_ID: ${{ 1f9c8772d72e7b8f65adb77ff3253fe5584daa1d62dd37372fd39ef2805239b8.CC_TEST_REPORTER_ID }}
        with:
          coverage_command: make test-cov
