name: GitHub-Actions
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses:  actions/checkout@v3
    
      - name: Install poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          make install

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cloning repository
        uses:  actions/checkout@v3
  
      - name: Check lint
        run: |
          pwd
          make lint
        
  test:
    runs-on: ubuntu-latast
    needs : build
    steps:
      - name: Cloning repository
        uses:  actions/checkout@v3

      - name: Check tests
        run: make test
      
