name: GitHub-Actions
on:
  - push
  - pull_request

jobs:
  build-and-lint-and-test :
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses:  actions/checkout@v3
    
      - name: Install poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          make install

      - name: Check lint
        run: make lint

      - name: Chek tests
        run: make test
